### ISSUE TITLE
Find a good task for Lora

### ISSUE THREAD

**Issue by dlwh** [stanford-crfm/levanter#358]
Alpaca Lora isn't any good, we should find something that works well

**Comment by Ivan-Zhou** [comment]
What aspects of Alpaca's LoRA are you not satisfied about? Are you looking for some tasks that are more applicable/common?

**Comment by dlwh** [comment]
both our reproduction and the original alpaca lora repo for some reason refuse to spit out EOS, so the results don't look good. So I'd either like to fix Alpaca LoRA or find a better suited task

**Comment by Ivan-Zhou** [comment]
If the main issue is the inability to produce EOS, maybe starting with Llama2-7B-chat will help. 

From my work, I have seen several examples of query-to-json: given a question, answer in a structured format like JSON, so that it can be easily digested by backend. The task is straightforward and the model's improvements after fine-tuning is obvious. I would consider it a good task for demo-purpose. I couldn't find good example datasets from public. The training data can be generated from GPT-4, if we have credits. 

While I was researching on public datasets for fine-tuning, I found this [OpenOrca](https://huggingface.co/datasets/Open-Orca/OpenOrca?row=9) dataset that contains 1M examples that were sampled from FLAN-v2 and contains detailed explanation with GPT-4 from answering. If our concern is about the data quality and quantity, this might be a better alternative than 52K Alpaca.

**Comment by dlwh** [comment]
we have two now!
